### PR TITLE
Impala

### PR DESCRIPTION
**Pull request by korneliusracz**

### CODE REVIEW

**Comment by schuemie** [comment]
First of all, I think the right solution here would be to build support for dates into Impala, Second, I think I prefer that, until Impala is fixed, it might be better to use the following hack instead of adding these random bits of code to all OHDSI tools:

What if we add some rules to DatabaseConnector where for Impala any field with a name ending in '_date' is automatically converted to DATE?

Then, once support for dates is added to Impala we have one place to remove our hacks.

**Comment by korneliusracz** [comment]
I agree. Impala itself should have support for DATE type.

The hack you are suggesting is basically the hack that I inserted into
CohortMethod, am I right?
Hence, then what you are suggesting is to move my hack to DatabaseConnector.

Please let me know and I will modify DatabaseConnector accordingly.

Thanks.

Cornelius

**Comment by schuemie** [comment]
Yes, that is right, it's the same hack, but a bit more generic (for all _date fields).

I recommend adding some lines to the lowLevelQuerySql and lowLevelQueySql.ffdf functions. Note that both have an argument datesAsString which, if true, should just give the behavior Impala currently has.

**Comment by korneliusracz** [comment]
I created a new pull request for DatabaseConnector. I actually modified
querySql and querySql.ffdf (not lowLevelQuery), adding the "hack" we
discussed.

Cornelius

**Pull request closed without merging**
